[build]
builder = "paketobuildpacks/builder:base"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"


[build]
builder = "RAILPACK"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
useLegacyStacker = false
multiRegionConfig = {"europe-west4-drams3a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
